services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4318:4318"
      - "4317:4317"
    environment:
      - LOG_LEVEL=debug
    networks:
      - observer-net
#
#  zipkin:
#    image: openzipkin/zipkin:latest
#    ports:
#      - '9411:9411'
#    networks:
#      - observer-net

#  grafana:
#    image: grafana/grafana:latest
#    ports:
#      - '3000:3000'
#    networks:
#        - observer-net
#
#  prometheus:
#    image: prom/prometheus:latest
#    container_name: prometheus
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#    networks:
#      - observer-net

networks:
  observer-net:
    driver: bridge
    name: observer-net
